# Generated by Django 4.1.6 on 2023-04-18 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Convict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("aliases", models.CharField(max_length=500)),
                ("gender", models.CharField(max_length=20)),
                ("place_of_birth", models.CharField(max_length=510)),
                ("place_of_birth_type", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                ("education", models.CharField(blank=True, max_length=100)),
                ("financial_background", models.CharField(blank=True, max_length=100)),
                ("family_record", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charges", models.CharField(max_length=100)),
                (
                    "charges_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("crime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("known_accomplices", models.CharField(blank=True, max_length=100)),
                ("fir_date", models.DateField(blank=True)),
                (
                    "conviction_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("comments", models.TextField(blank=True, max_length=300)),
                ("sentencer", models.CharField(blank=True, max_length=100)),
                ("sentence", models.CharField(blank=True, max_length=100)),
                (
                    "perp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.convict"
                    ),
                ),
            ],
        ),
    ]
