# Generated by Django 4.1.6 on 2023-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_convict_block_perp"),
    ]

    operations = [
        migrations.AddField(
            model_name="convict",
            name="crime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="convict",
            name="family_record",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="convict",
            name="place_of_birth_type",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="block",
            name="charges_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
