# Generated by Django 4.1.6 on 2023-04-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_convict_crime_type_convict_family_record_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convict",
            name="crime_type",
        ),
        migrations.AddField(
            model_name="block",
            name="crime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
